### ISSUE TITLE
Code review and feedback

### ISSUE THREAD

**Issue by Rarst** [baardbaard/bb-twitterfeed#14]
Hey, getting to that code review as you asked. :)
1. You require class files explicitly. Fine for a plugin small enough, but generally this is something Composer autoload should handle. It can pick up arbitrary classes with classmap.
2. `bbtf()` function seems is out of place. The name is not descriptive and it just passes call through.
3. Singleton is bad pattern. In WP code it's usually remnant of faux–OOP, which uses classes as fake namespacing. In modern code anything singleton does dependency injection will do better (not that it's necessary for plugin this small).
4. Somewhat related to previous point the single main class has too much going on. Things like translations set up are not logically related to Twitter functionality. Again, it's a small plugin _now_, but these things grow fast. Classes should have clear separated responsibility to what they do.
5. Some `$twitter_error` seems to miss `$this->` here and there.
6. `build_tweets_list()` is bulky. if/else should typically be early returns instead and count of nesting should be minimal.
7. HTML templating seems to not have enough escaping and trusting to a third party input (API returns). Personally I like to implement plugin templating with Mustache, but yet again — small enough plugin to bother with proper templating engine probably.

**Comment by stefthoen** [comment]
Thanks, I appreciate it. What you're saying makes total sense and I'll start working on it. About point 1. Do you perhaps an article that explains it a little bit?

**Comment by Rarst** [comment]
See Composer docs on autoload in general and classmap specifically: https://getcomposer.org/doc/04-schema.md#classmap

**Comment by stefthoen** [comment]
Regarding Mustache. Is there any reason why you use JavaScript for this? Aren't there any PHP templating engines available? Like Smarty or Twig?

**Comment by Rarst** [comment]
Mustache is highly cross–language and has a great PHP port: https://github.com/bobthecow/mustache.php

I prefer it over Twig for plugins since it has less stuff and ensures more strict separation. I prefer Twig for themes.

**Comment by stefthoen** [comment]
I implemented all your suggestions. If you want to and have the time, could you tell me how I did and if you still see room for improvement? I appreciate it a lot.

**Comment by Rarst** [comment]
Organization looks better from a quick look, don't want to go through _all_ of it again at the moment. :)
